name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # - uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          # image_tag: ${{ steps.package-version.outputs.current-version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
